languageCode = "en"
languageName = "English"
weight = 1
title = "Cyano-genesis"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Cyano's record of projects, thoughts, and other random stuff."
dateFormat = "January 2, 2006"
author = { name = "Cyano Hibiki", headline = "Researcher, Maker, Gamer, Casual Programmer", bio = "Maintainer." }
# copyright = "© { year } Cyano Hibiki"

